- hosts: all
  tasks:
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest


  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: install unzip
    yum:
      name: unzip
      state: latest

  - name: Extraxt files
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page280/klassy-cafe.zip
      dest: /var/www/html/
      remote_src: yes

  - name: Disable SELinux
    selinux:
      state: disabled
